### ISSUE TITLE
Expose UI option to limit organization-access to certain domains

### ISSUE THREAD

**Issue by eraz** [vidalborromeo/eecshelp-beta#2]
v2.30

The login process does not appear to limit access to @umich.edu addresses.

Any Google account (or login-through-google services) can sign in.

**Comment by vidalborromeo** [comment]
That's by design (and also useful for the purposes of testing).
**_That said_**... I included backend support for allowing course-moderators to limit access to just certain domains, but I never got around to exposing that option in the UI. Thanks for the reminder!

I'll rename this issue and add a "Feature Request" tag.

**Comment by vidalborromeo** [comment]
This issue was moved to vidalborromeo/eecshelp-queue#1

**Comment by vidalborromeo** [comment]
Moved this issue over to the official issue tracker.
